-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 14:24:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------

-- Table `joboffers`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `joboffers`(

  `joboffer_id` INT NOT NULL AUTO_INCREMENT,

  `joboffer_title` VARCHAR(255) NOT NULL,

  `joboffer_description` TEXT NOT NULL,

  `joboffer_price` INT NOT NULL,

  `joboffer_isWorker` VARCHAR(30) NOT NULL,

  `joboffer_localisation` VARCHAR(100) NOT NULL,

  `joboffer_image` TEXT NOT NULL,

  `joboffer_duration` INT,

  `joboffer_createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  `user_email` VARCHAR(80) NOT NULL,

  `user_filiere` VARCHAR(80) NOT NULL,

  `user_name` VARCHAR(50) NOT NULL,

  `user_phone` VARCHAR(10),

  `user_discord` VARCHAR(255),

  PRIMARY KEY (`joboffer_id`)

);

INSERT INTO joboffers (
  joboffer_title,
  joboffer_description,
  joboffer_price,
  joboffer_isWorker,
  joboffer_localisation,
  joboffer_image,
  joboffer_duration,
  user_email,
  user_filiere,
  user_name,
  user_phone,
  user_discord
) VALUES 
('Offre d\'emploi 1', 'Description de l\'offre 1', 1000, 'Oui', 'Lyon, France', 'image1.jpg', 12, 'email1@example.com', 'Informatique', 'John Doe', '1234567890', 'john.doe#1234'),
('Offre d\'emploi 2', 'Description de l\'offre 2', 800, 'Non', 'Paris, France', 'image2.jpg', 6, 'email2@example.com', 'Marketing', 'Alice Smith', '9876543210', 'alice.smith#5678'),
('Offre d\'emploi 3', 'Description de l\'offre 3', 1200, 'Oui', 'Berlin, Allemagne', 'image3.jpg', 9, 'email3@example.com', 'Ingénierie', 'Bob Johnson', '5555555555', 'bob.johnson#9999'),
('Offre d\'emploi 4', 'Description de l\'offre 4', 600, 'Non', 'New York, États-Unis', 'image4.jpg', 3, 'email4@example.com', 'Ventes', 'Eva Brown', '1111111111', 'eva.brown#7777'),
('Offre d\'emploi 5', 'Description de l\'offre 5', 1500, 'Oui', 'Londres, Royaume-Uni', 'image5.jpg', 12, 'email5@example.com', 'Finance', 'Sophie White', '2222222222', 'sophie.white#5555'),
('Offre d\'emploi 6', 'Description de l\'offre 6', 700, 'Non', 'Barcelone, Espagne', 'image6.jpg', 6, 'email6@example.com', 'Ressources humaines', 'David Green', '3333333333', 'david.green#8888'),
('Offre d\'emploi 7', 'Description de l\'offre 7', 1100, 'Oui', 'Sydney, Australie', 'image7.jpg', 9, 'email7@example.com', 'Médical', 'Laura Wilson', '4444444444', 'laura.wilson#6666'),
('Offre d\'emploi 8', 'Description de l\'offre 8', 900, 'Non', 'Tokyo, Japon', 'image8.jpg', 6, 'email8@example.com', 'Éducation', 'Michael Lee', '9999999999', 'michael.lee#1111'),
('Offre d\'emploi 9', 'Description de l\'offre 9', 1300, 'Oui', 'Toronto, Canada', 'image9.jpg', 12, 'email9@example.com', 'Art', 'Olivia Taylor', '7777777777', 'olivia.taylor#4444'),
('Offre d\'emploi 10', 'Description de l\'offre 10', 750, 'Non', 'Mexico City, Mexique', 'image10.jpg', 3, 'email10@example.com', 'Ingénierie', 'Daniel Garcia', '6666666666', 'daniel.garcia#2222');
